apiVersion: v1
kind: Service
metadata:
  name: blog-posts-srv
spec:
  type: NodePort
  selector:
    app: posts
  ports:
    - name: posts
      protocol: TCP
      port: 4000
      targetPort: 4000
      nodePort: 31515
    - name: posts-cluster
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 31516
